// Real Accounts & Taxation Executive test — 20 MCQ, single mark each.
const ACCOUNTS_QUESTIONS = [
  { text: "As per the Income Tax Act, TDS under Section 194C (payment to contractors) is applicable when a single payment exceeds \u20b9____ or the aggregate payment in a financial year exceeds \u20b9____.",
    options: ["\u20b930,000 / \u20b91,00,000", "\u20b920,000 / \u20b975,000", "\u20b950,000 / \u20b91,50,000", "\u20b910,000 / \u20b950,000"],
    correct: 0 },
  { text: "What is the standard rate of TDS under Section 194J for professional fees paid to a resident?",
    options: ["2%", "5%", "10%", "1%"],
    correct: 2 },
  { text: "Section 194Q (TDS on purchase of goods) applies when the buyer's turnover in the preceding financial year exceeds \u20b9____ and purchases from a single seller exceed \u20b9____ during the year.",
    options: ["\u20b95 Crore / \u20b950 Lakh", "\u20b910 Crore / \u20b950 Lakh", "\u20b91 Crore / \u20b925 Lakh", "\u20b910 Crore / \u20b91 Crore"],
    correct: 1 },
  { text: "If eligible TDS is not deducted or deposited on an expense, what percentage of that expense is disallowed under Section 40(a)(ia) while computing business income?",
    options: ["100%", "50%", "30%", "20%"],
    correct: 2 },
  { text: "Which of the following is NOT a standard GST rate slab in India?",
    options: ["5%", "12%", "18%", "22%"],
    correct: 3 },
  { text: "Under the Reverse Charge Mechanism (RCM) in GST, who is primarily liable to pay tax to the government?",
    options: ["Supplier of goods/services", "Recipient of goods/services", "GST department directly", "E-commerce operator only"],
    correct: 1 },
  { text: "Input Tax Credit (ITC) can be validly claimed by a recipient only if the supplier's invoice details are reflected in which statement/return?",
    options: ["GSTR-3B only", "GSTR-1 of the recipient", "GSTR-2B", "GSTR-9"],
    correct: 2 },
  { text: "What is the primary difference between GSTR-1 and GSTR-3B?",
    options: ["GSTR-1 reports outward supply invoice details; GSTR-3B is a summary return for tax payment", "GSTR-1 is a monthly summary; GSTR-3B is invoice-wise", "Both are identical and filed as a backup of each other", "GSTR-1 is annual; GSTR-3B is quarterly"],
    correct: 0 },
  { text: "As per current GST rules, e-invoicing is mandatory for businesses with aggregate turnover exceeding:",
    options: ["\u20b950 Crore", "\u20b920 Crore", "\u20b95 Crore", "\u20b91 Crore"],
    correct: 2 },
  { text: "Under the GST Composition Scheme, the aggregate annual turnover limit for suppliers of goods (normal category states) is:",
    options: ["\u20b975 Lakh", "\u20b91 Crore", "\u20b91.5 Crore", "\u20b92 Crore"],
    correct: 2 },
  { text: "Which of the following is NOT one of the Five Heads of Income under the Income Tax Act?",
    options: ["Income from Salary", "Income from House Property", "Income from Foreign Investments", "Capital Gains"],
    correct: 2 },
  { text: "What is the standard deduction allowed on Net Annual Value under \u201cIncome from House Property\u201d as per Section 24(a)?",
    options: ["20%", "30%", "25%", "50%"],
    correct: 1 },
  { text: "What is the maximum deduction limit available under Section 80C of the Income Tax Act (old regime)?",
    options: ["\u20b91,00,000", "\u20b91,50,000", "\u20b92,00,000", "\u20b92,50,000"],
    correct: 1 },
  { text: "Under Section 44AD (Presumptive Taxation Scheme), what percentage of turnover is deemed as profit when receipts are through digital/banking channels?",
    options: ["8%", "6%", "10%", "12%"],
    correct: 1 },
  { text: "What is the standard employee contribution rate towards Provident Fund (PF) on basic wages + DA?",
    options: ["10%", "12%", "15%", "8.33%"],
    correct: 1 },
  { text: "As per current rules, ESI (Employees' State Insurance) is applicable to employees whose gross monthly wage does not exceed:",
    options: ["\u20b915,000", "\u20b921,000", "\u20b925,000", "\u20b918,000"],
    correct: 1 },
  { text: "Form 16 issued to employees is a TDS certificate specifically for:",
    options: ["Salary income", "Professional fees", "Rent payments", "Contractor payments"],
    correct: 0 },
  { text: "\u201cDebit what comes in, Credit what goes out\u201d is the golden rule applicable to which type of account?",
    options: ["Personal Account", "Real Account", "Nominal Account", "Suspense Account"],
    correct: 1 },
  { text: "Which depreciation method is mandatorily used for computing depreciation under the Income Tax Act for most blocks of assets?",
    options: ["Straight Line Method (SLM)", "Written Down Value (WDV) Method", "Units of Production Method", "Sum of Years' Digits Method"],
    correct: 1 },
  { text: "A Bank Reconciliation Statement (BRS) is primarily prepared to:",
    options: ["Calculate the monthly GST liability", "Match the cash book balance with the bank passbook/statement balance and identify discrepancies", "Compute TDS liability on bank interest", "Prepare the balance sheet directly"],
    correct: 1 },
];