// Real Aptitude Test question bank — shared by Sales and Commodity tracks.
// Section 1: Verbal (10) · Section 2: Logical (10)
const APTITUDE_QUESTIONS = [

  // ── SECTION 1: VERBAL ──
  { text: "Identify the correct sentence:",
    options: ["Each of the students have completed their assignments.", "Every student have submitted the project.", "Neither of the options is correct.", "One of the students have done well.", "None of the above."],
    correct: 2 },
  { text: "Choose the most appropriate word: He is known for his ____ attitude, always seeing the negative.",
    options: ["optimistic", "pessimistic", "realistic", "narcissistic", "sarcastic"],
    correct: 1 },
  { text: "Fill in the blank: She was hesitant to speak up, ____ she knew the answer.",
    options: ["because", "while", "although", "unless", "until"],
    correct: 2 },
  { text: "Choose the synonym of \u201cMitigate\u201d:",
    options: ["Ignore", "Intensify", "Reduce", "Complicate", "Announce"],
    correct: 2 },
  { text: "One word substitution: A person who believes in fate",
    options: ["Fatalist", "Optimist", "Pessimist", "Realist", "Altruist"],
    correct: 0 },
  { text: "Select the correct idiom: \u201cBurning the midnight oil\u201d means:",
    options: ["Getting into trouble", "Sleeping early", "Working late", "Enjoying nightlife", "Losing patience"],
    correct: 2 },
  { text: "Choose the correct form: Neither of the girls ____ present.",
    options: ["are", "have", "is", "were", "will"],
    correct: 2 },
  { text: "Fill in the blank: The manager gave him a warning due to his ____ behavior.",
    options: ["exemplary", "inspiring", "inappropriate", "punctual", "excellent"],
    correct: 2 },
  { text: "Choose the sentence with correct subject-verb agreement:",
    options: ["The data is unreliable and are constantly changing.", "The team are going to win.", "The criteria for selection is strict.", "The phenomenon of storms is well-documented.", "None of the above."],
    correct: 3 },
  { text: "Choose the correct usage of the word \u201ceffect\u201d:",
    options: ["The new law effected changes overnight.", "This medicine will effect your blood pressure.", "The effect of the speech was negative.", "A and C", "All of the above"],
    correct: 3 },

  // ── SECTION 2: LOGICAL ──
  { text: "What comes next: 5, 11, 23, 47, ?",
    options: ["94", "95", "92", "96", "90"],
    correct: 1 },
  { text: "Odd one out:",
    options: ["Square", "Triangle", "Circle", "Hexagon", "Rectangle"],
    correct: 2 },
  { text: "MANGO = 131145, APPLE = 155123. What is the code for GRAPE?",
    options: ["791115", "715125", "718125", "791125", "715135"],
    correct: 2 },
  { text: "Spot the pattern: ACE, BDF, ?",
    options: ["CEG", "CFI", "CEH", "BDG", "CFG"],
    correct: 0 },
  { text: "Direction: Ram walks 4 km north, then 3 km east, then 4 km south. How far is he from the starting point?",
    options: ["3 km", "4 km", "5 km", "6 km", "7 km"],
    correct: 0 },
  { text: "A is the mother of B. B is the father of C. How is A related to C?",
    options: ["Sister", "Aunt", "Grandmother", "Niece", "Mother"],
    correct: 2 },
  { text: "MANGO = 131145, APPLE = 155123. What is the code for GRAPE?",
    options: ["791115", "715125", "718125", "791125", "715135"],
    correct: 4 },
  { text: "Re-arrange to form a meaningful sentence: 1. the exam  2. she prepared  3. well for  4. and succeeded  5. in flying colours",
    options: ["2-3-1-4-5", "1-3-2-5-4", "3-1-2-4-5", "5-4-3-2-1", "2-4-1-3-5"],
    correct: 0 },
  { text: "Puzzle: 5 people \u2013 A, B, C, D, E \u2013 are sitting in a row. A is to the left of B but right of C. D is to the right of B. E is between C and A. Who is sitting at the leftmost position?",
    options: ["A", "B", "C", "E", "D"],
    correct: 2 },
  { text: "In a code language, TRUST = 64321, STARS = 12345. What is the code for START?",
    options: ["14563", "12341", "14321", "15324", "15423"],
    correct: 1 },
];