// Real Commodity Test question bank — NISM Series VIII (Equity Derivatives) style, 10 MCQ.
const COMMODITY_QUESTIONS = [
  { text: "What is a derivative?",
    options: ["A type of bank deposit", "A financial instrument whose value is derived from an underlying asset", "A fixed-income security", "A savings product"],
    correct: 1 },
  { text: "Which of the following is an equity derivative?",
    options: ["Stock dividend", "Equity share", "Stock future", "Mutual fund"],
    correct: 2 },
  { text: "A futures contract is:",
    options: ["An agreement to buy or sell an asset at a fixed price on a future date", "A right to buy an asset without obligation", "A bank loan", "A cash dividend"],
    correct: 0 },
  { text: "An option buyer has:",
    options: ["An obligation to exercise the contract", "No right in the contract", "The right, but not the obligation, to buy or sell", "Ownership of the underlying asset immediately"],
    correct: 2 },
  { text: "A call option gives the buyer the right to:",
    options: ["Sell the underlying asset", "Buy the underlying asset", "Borrow money", "Receive interest"],
    correct: 1 },
  { text: "The strike price is:",
    options: ["The market price on the expiry date", "The price at which an option can be exercised", "The premium paid to the broker", "The amount of margin blocked"],
    correct: 1 },
  { text: "Margin in derivatives trading is:",
    options: ["A discount on brokerage", "Money deposited to cover possible losses", "The profit earned on expiry", "A tax on trading"],
    correct: 1 },
  { text: "The expiry date is:",
    options: ["The date when the contract becomes invalid", "The first date of trading", "The date of dividend payment", "The date margin is refunded"],
    correct: 0 },
  { text: "Mark-to-market means:",
    options: ["Buying at the opening price", "Daily settlement of gains and losses based on market prices", "Closing all positions manually", "Setting the strike price"],
    correct: 1 },
  { text: "Open interest refers to:",
    options: ["Total number of outstanding contracts not yet closed or settled", "Number of brokers in the market", "Quantity traded in cash market only", "Interest paid on deposits"],
    correct: 0 },
];