// Real Commodity Combined Test question bank (NISM 8 + 16) — 27 MCQ.
// Note: 3 questions from the source paper were left out as they were
// not multiple-choice — a True/False question and two open-ended
// explanation questions.
const COMMODITY2_QUESTIONS = [
  { text: "Which of the following correctly represents Delta of a deep OTM call option sell?",
    options: ["-0.50", "0.50", "0.36", "-0.10"],
    correct: 2 },
  { text: "MCX commodity options are calculated with which of the following mathematical model:",
    options: ["Binomial Tree model", "Heston Stochastic Volatility model", "Black-Scholes Model", "Black-76 (Black\u2019s) Model"],
    correct: 3 },
  { text: "If future of underlying price moves by \u20b9100, how much option with Delta 0.3 moves (consider no change in any other Greeks)?",
    options: ["3", "33", "50", "30"],
    correct: 3 },
  { text: "In a call bull spread maximum loss is?",
    options: ["Buy leg premium - Sell leg premium", "Buy leg premium - Sell leg premium - Diff between strikes", "Sell leg premium - Buy leg premium - Diff between strikes", "Sell leg premium + Diff between strikes - Buy leg premium"],
    correct: 0 },
  { text: "If Bid price in a call option is \u20b950 and Ask price is \u20b9650 and you buy it at Market price, at what price will your order get filled?",
    options: ["50", "650", "350", "100"],
    correct: 1 },
  { text: "Dow Theory is based on the movement of",
    options: ["Option price", "Interest Rate", "Stock market price trends", "Implied volatility"],
    correct: 2 },
  { text: "Higher Volatility means",
    options: ["Higher premiums of call option", "Higher premiums of call & put option", "Lower premiums of Put option", "Higher premiums of put option"],
    correct: 1 },
  { text: "Timing for commodity (MCX) in winter is",
    options: ["9 AM - 11:30 PM", "9:15 AM - 11:45 PM", "9 AM - 11:55 PM", "9:15 AM - 3:30 PM"],
    correct: 2 },
  { text: "SCORES is used for which of the following:",
    options: ["To trade on clients account", "Used by SEBI to score or rate exchanges performance", "Used for registering & resolving investors complaints", "Calculating margin requirements"],
    correct: 2 },
  { text: "A mark-to-market settlement in futures primarily reduces:",
    options: ["Liquidity risk", "Credit risk", "Interest rate risk", "Operational risk"],
    correct: 1 },
  { text: "Which statement about operational risk is true?",
    options: ["It cannot be reduced through internal controls.", "It arises only due to technology failures.", "It includes losses resulting from inadequate or failed processes, people, systems, or external events.", "It affects only banks, not brokers."],
    correct: 2 },
  { text: "A dealer places trades in a client\u2019s account without authorization in an attempt to recover previous losses. This is an example of:",
    options: ["External fraud", "Internal fraud leading to operational risk", "Liquidity risk", "Market risk"],
    correct: 1 },
  { text: "State the difference between Bull Call Spread and Call Debit Spread.",
    options: ["BC spread is for bullish and CD is for bearish market", "BC spread is for bullish and CD is sideways market", "BC spread is for bearish and CD is for bullish market", "None of the above"],
    correct: 3 },
  { text: "A trader expects moderate bullish movement in gold.",
    options: ["Put credit spread", "Bull put spread", "Call credit spread", "CE ratio"],
    correct: 1 },
  { text: "Can we place orders in pre-open market?",
    options: ["Yes", "No"],
    correct: 0 },
  { text: "A trader buys a NIFTY futures at 24,500. Lot size is 75. Future price first rises to 24,967, then closed at 24,220. Position is carried for the next day. What\u2019s the MTM at end of day?",
    options: ["21,000", "35,020", "56,025", "35,025"],
    correct: 3 },
  { text: "Which Greek measures the rate of change of premium with respect to interest rate?",
    options: ["Rho", "Black & Scholes", "Vega", "Time Value"],
    correct: 0 },
  { text: "An investor expects high volatility but has no directional view. Which strategy is most appropriate?",
    options: ["Covered Call", "Long Straddle", "Bull Call Spread", "Bear Put Spread"],
    correct: 1 },
  { text: "A jeweller expects to purchase 100 kg of silver after 3 months. Next day he decided to have another 20 kg. To hedge against rising prices, the jeweller should trade how many lots of silver?",
    options: ["Buy 4 lots silver main or buy 24 lot silver M", "Buy 5 lots silver main or buy 30 lot silver M", "Buy 8 lots silver main or buy 20 lot silver M", "Buy 4 lots silver main or buy 32 lot silver M"],
    correct: 0 },
  { text: "A stock gains 10% on Monday and loses 10% on Tuesday. The final price equals?",
    options: ["Closing price of Monday", "Closing price on Friday", "Closing price on Tuesday", "Opening price of Wednesday"],
    correct: 2 },
  { text: "Find the brokerage if trade value is \u20b95,00,000 and brokerage is 0.02%.",
    options: ["200", "100", "150", "300"],
    correct: 1 },
  { text: "Which option trader loses value due to time decay if all other factors remain unchanged?",
    options: ["Option buyer", "Option seller"],
    correct: 0 },
  { text: "A call option has delta of 0.60. If the underlying rises by \u20b910, approximately how much will the option premium increase?",
    options: ["6", "60", "0.60", "30"],
    correct: 0 },
  { text: "What is the maximum loss when buying a call option?",
    options: ["Premium paid + lot size", "Premium paid - lot size", "Premium paid / lot size", "Premium paid \u00d7 lot size"],
    correct: 3 },
  { text: "You buy a 26,000 call for \u20b9180. What is the break-even at expiry?",
    options: ["25820", "26180", "26360", "26000"],
    correct: 1 },
  { text: "You are long 200 call options with a delta of 0.65. How many shares should you short to make the position delta-neutral?",
    options: ["130", "160", "200", "250"],
    correct: 0 },
  { text: "A call option has delta 0.50 and gamma 0.08. If the underlying rises by \u20b92, what is the new delta?",
    options: ["0.66", "0.58", "0.42", "-0.58"],
    correct: 0 },
];