// Real Sales Test question bank — 18 multiple-choice questions.
// (The 5 "Basic Finance" open-ended questions from the source document
// were left out per instruction — descriptive/non-gradable questions
// aren't included in this test.)
const SALES_QUESTIONS = [
  { text: "What does IPO stand for?",
    options: ["Initial Price Offering", "Initial Public Offering", "Internal Public Option", "Investment Public Offering"],
    correct: 1 },
  { text: "Which regulatory body governs the Indian securities market?",
    options: ["RBI", "IRDAI", "SEBI", "NABARD"],
    correct: 2 },
  { text: "Which index represents 50 major companies listed on NSE?",
    options: ["Sensex", "Nifty", "BSE", "NSE"],
    correct: 1 },
  { text: "What does EPS stand for?",
    options: ["Earnings per Share", "Equity per Stock", "Estimated Price Share", "Earnings Price Standard"],
    correct: 0 },
  { text: "Which financial statement shows a company's profitability?",
    options: ["Balance Sheet", "Cash Flow Statement", "Income Statement (P&L Account)", "Trial Balance"],
    correct: 2 },
  { text: "Which ratio is used to evaluate the valuation of a stock?",
    options: ["Current Ratio", "Debt-Equity Ratio", "P/E Ratio", "Quick Ratio"],
    correct: 2 },
  { text: "What does DCF stand for?",
    options: ["Discounted Cash Flow", "Direct Cash Fund", "Debt Cash Flow", "Dividend Cash Formula"],
    correct: 0 },
  { text: "Which of the following is a derivative instrument?",
    options: ["Equity Shares", "Bonds", "Futures Contract", "Fixed Deposit"],
    correct: 2 },
  { text: "Which institution decides the Repo Rate in India?",
    options: ["SEBI", "RBI", "NSE", "Ministry of Finance"],
    correct: 1 },
  { text: "Which risk cannot be eliminated through diversification?",
    options: ["Business Risk", "Company Risk", "Unsystematic Risk", "Systematic Risk"],
    correct: 3 },
  { text: "What does ROE stand for?",
    options: ["Return on Equity", "Rate of Earnings", "Return on Expense", "Revenue on Equity"],
    correct: 0 },
  { text: "Which market deals with the buying and selling of existing securities?",
    options: ["Primary Market", "Secondary Market", "Commodity Market", "Forex Market"],
    correct: 1 },
  { text: "Which among the following is NOT a financial statement?",
    options: ["Balance Sheet", "Profit & Loss Account", "Cash Flow Statement", "Market Share Statement"],
    correct: 3 },
  { text: "What is the full form of NAV in mutual funds?",
    options: ["Net Asset Value", "National Asset Value", "Net Average Value", "National Average Valuation"],
    correct: 0 },
  { text: "Which ratio measures a company's ability to meet short-term obligations?",
    options: ["P/E Ratio", "Current Ratio", "ROE", "EBITDA Margin"],
    correct: 1 },
  { text: "Which type of analysis studies charts and price movements?",
    options: ["Fundamental Analysis", "Ratio Analysis", "Technical Analysis", "Vertical Analysis"],
    correct: 2 },
  { text: "What is EBITDA?",
    options: ["Earnings before Interest, Taxes, Depreciation and Amortization", "Earnings Before Income and Tax Adjustments", "Estimated Business Income Tax Analysis", "Earnings Balance Tax Account"],
    correct: 0 },
  { text: "Diversification helps in reducing:",
    options: ["Inflation Risk", "Interest Rate Risk", "Unsystematic Risk", "Market Risk"],
    correct: 2 },
];